### ISSUE TITLE
Maybe it is better to mark each color as `Stable`

### ISSUE THREAD

**Issue by FunnySaltyFish** [atick-faisal/compose-material-color#2]
Mark color as `@Stable` can help Compose compiler do optimization. If you check the source code of `androidx/compose/ui/graphics/Color.kt`, you can find this annotation.  And you can refer to [this blog](https://chris.banes.dev/composable-metrics/) to learn more about `@Stable` .

By the way, I've written a [similar library](https://github.com/FunnySaltyFish/CMaterialColors/blob/master/lib/src/main/java/com/funny/cmaterialcolors/CMaterialColors.kt) as well(which considers this question) :)

**Comment by atick-faisal** [comment]
Thank you so much for pointing this out. I have added your suggestion to the [code](https://github.com/atick-faisal/compose-material-color/commit/754cfd18cb71255c832133bde96da40209cf0163). [New library version 3.0.0 is out](https://github.com/atick-faisal/compose-material-color/releases/tag/3.0.0) with the changes and dependency bumps.
